name: Post JSON File to Three URLs
on:
  schedule:
    - cron: '0 * * * *' # Elke uur
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  post_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send JSON Data to First URL (Temperature)
        run: |
          curl -X POST "https://:8FdxW7mYTHa3Sv6fusWEmg@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:CoubJeakRc28U41oqrqZHw/streams/AQAAAJbP48cLOU7UhMTN3yP3G7YAAAAA" \
               -H "Content-Type: application/json" \
               -d @stream.json

      - name: Send JSON Data to Second URL (Humidity)
        run: |
          curl -X POST "https://:weV8yipxQke-Zuj3hiO9uQ@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:CoubJeakRc28U41oqrqZHw/streams/AQAAADjJHPu66kPpoxcRWnkgUn4AAAAA" \
               -H "Content-Type: application/json" \
               -d @stream.json

      - name: Send JSON Data to Third URL (CO2)
        run: |
          curl -X POST "https://:VAuTX-tlRuGVSExwEe5c9Q@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:CoubJeakRc28U41oqrqZHw/streams/AQAAAE8L6neAPUYhm-rWCrCr3akAAAAA" \
               -H "Content-Type: application/json" \
               -d @stream.json

             
